// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO9Ef8ScwWzYFVjU_QbQWrTNkNB0vb8CA',
    appId: '1:648452668549:android:8dc35dc8f7b9f0b1853dec',
    messagingSenderId: '648452668549',
    projectId: 'cse-project-2100',
    storageBucket: 'cse-project-2100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzZXgN5urevMDTvN5g3Ba2QlCohfinkXc',
    appId: '1:648452668549:ios:58295d7ae0ac0c8f853dec',
    messagingSenderId: '648452668549',
    projectId: 'cse-project-2100',
    storageBucket: 'cse-project-2100.firebasestorage.app',
    iosBundleId: 'com.example.cseProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVK4qmTRL03ZuJFsPif75W2GiFFaAV-ZE',
    appId: '1:648452668549:web:409250a5c9719669853dec',
    messagingSenderId: '648452668549',
    projectId: 'cse-project-2100',
    authDomain: 'cse-project-2100.firebaseapp.com',
    storageBucket: 'cse-project-2100.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzZXgN5urevMDTvN5g3Ba2QlCohfinkXc',
    appId: '1:648452668549:ios:58295d7ae0ac0c8f853dec',
    messagingSenderId: '648452668549',
    projectId: 'cse-project-2100',
    storageBucket: 'cse-project-2100.firebasestorage.app',
    iosBundleId: 'com.example.cseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVK4qmTRL03ZuJFsPif75W2GiFFaAV-ZE',
    appId: '1:648452668549:web:3918fc69e91b31dd853dec',
    messagingSenderId: '648452668549',
    projectId: 'cse-project-2100',
    authDomain: 'cse-project-2100.firebaseapp.com',
    storageBucket: 'cse-project-2100.firebasestorage.app',
  );

}